name: CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # See also https://github.com/flatpak/flatpak-github-actions
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak gettext # FIXME use flatpak sdk for msgfmt tests
          version: 1.0

      - name: Cache Flatpak dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/flatpak
          key: 45beta

      - run: make ci

  flatter:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Runtimes
        run: |
          flatpak install -y --noninteractive \
                          flathub \
                          org.flatpak.Builder \
                          org.freedesktop.Sdk//23.08 \
                          org.freedesktop.Sdk.Extension.rust-stable//23.08 \
                          org.freedesktop.Sdk.Extension.node18//23.08 \
                          org.freedesktop.Sdk.Extension.vala//23.08 \
                          org.freedesktop.Sdk.Extension.llvm16//23.08
          flatpak install -y --noninteractive \
                          flathub-beta \
                          org.gnome.Platform//45beta \
                          org.gnome.Sdk//45beta \
                          org.gnome.Sdk.Docs//45beta

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/re.sonny.Workbench.Devel.json
          upload-bundles: true
